project:
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "502"
  date: "2024-11-22"
  chapters:
    - index.qmd
    - 01-Reliabilitet.qmd
    - 02-Regresjonsmodellar.qmd
    - 03-Statistisk_inferens.qmd
    - 04-Studiedesign.qmd
    - 05-Analysere_eksperiment_med_gjentatte_m√•lingar.qmd
    - 06-Vitenskapsteori.qmd
    - 07-laboratory-report.qmd
    - Referansar.qmd

bibliography: bibliografi.bib

format: pdf




